import { test, expect, type Page } from "@playwright/test";

test("two students form a team entirely through the browser", async ({ browser }) => {
  test.skip(!process.env.TEAMFIT_ISOLATED_TEST, "Run scripts/test.ps1 -Browser to avoid modifying real student data.");
  const suffix = Date.now();
  const password = "Browser-test-password!2026";
  const errors: string[] = [];
  const ownerContext = await browser.newContext();
  const memberContext = await browser.newContext();
  const owner = await ownerContext.newPage();
  const member = await memberContext.newPage();
  for (const page of [owner, member]) page.on("pageerror", error => errors.push(error.message));

  await owner.goto("/");
  await expect(owner.getByRole("heading", { name: "Campus Connect", exact: true })).toBeVisible();
  await expect(owner.getByRole("link", { name: "Browse projects", exact: true })).toHaveCount(0);
  await owner.goto("/projects");
  await expect(owner).toHaveURL(/\/login\?next=%2Fprojects$/);
  await expect(owner.getByRole("heading", { name: "Welcome back to TeamFit" })).toBeVisible();

  async function register(page: Page, email: string) {
    await page.goto("/register");
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Password", { exact: true }).fill(password);
    await page.getByRole("button", { name: "Register", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Create new profile" })).toBeVisible();
    await expect(page).toHaveURL(/\/profile\/create$/);
  }
  await register(owner, "browser-owner-" + suffix + "@example.test");
  await owner.getByLabel("Full name", { exact: true }).fill("Browser Owner");
  await owner.getByLabel("Preferred project role").selectOption("Frontend Developer");
  await owner.getByRole("combobox", { name: "Your skills" }).fill("React");
  await owner.getByRole("option", { name: "React", exact: true }).click();
  await expect(owner.getByRole("button", { name: "Remove React" })).toBeVisible();
  await expect(owner).toHaveURL(/\/profile\/create$/);
  await owner.getByRole("checkbox", { name: "Weekday Evening", exact: true }).check();
  await owner.getByRole("button", { name: "Save profile" }).click();
  await expect(owner).toHaveURL(/\/dashboard$/);
  await expect(owner.getByRole("heading", { name: "Welcome, Browser Owner" })).toBeVisible();
  await expect(owner.getByRole("navigation", { name: "Workspace navigation" })).toHaveCount(0);
  await owner.getByRole("banner").getByRole("link", { name: /My profile:/ }).click();
  await expect(owner.getByRole("button", { name: "Add profile picture", exact: true })).toContainText("B");
  const photo = { name: "avatar.png", mimeType: "image/png", buffer: await owner.screenshot({ clip: { x: 0, y: 0, width: 100, height: 100 } }) };
  await owner.getByLabel("Choose profile picture").setInputFiles(photo);
  const crop = owner.getByRole("dialog", { name: "Adjust profile picture" });
  await expect(crop).toBeVisible();
  await crop.getByRole("button", { name: "Cancel" }).click();
  await expect(owner.getByRole("button", { name: "Add profile picture", exact: true })).toContainText("B");
  await owner.getByLabel("Choose profile picture").setInputFiles(photo);
  await crop.getByRole("slider", { name: "Zoom" }).focus();
  await crop.getByRole("slider", { name: "Zoom" }).press("ArrowRight");
  const cropBounds = await crop.getByRole("img", { name: "Profile picture crop preview" }).boundingBox();
  if (!cropBounds) throw new Error("Crop preview is missing.");
  await owner.mouse.move(cropBounds.x + cropBounds.width / 2, cropBounds.y + cropBounds.height / 2);
  await owner.mouse.down();
  await owner.mouse.move(cropBounds.x + cropBounds.width / 2 + 12, cropBounds.y + cropBounds.height / 2 + 8);
  await owner.mouse.up();
  await crop.getByRole("img", { name: "Profile picture crop preview" }).press("ArrowLeft");
  await crop.getByRole("button", { name: "Save photo" }).click();
  const avatar = owner.getByRole("img", { name: "Browser Owner's profile picture", exact: true });
  await expect(avatar).toBeVisible();
  await expect.poll(() => avatar.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(512);
  await owner.reload();
  await expect(avatar).toBeVisible();
  await owner.goto("/dashboard");
  await expect(avatar).toBeVisible();
  await owner.getByRole("link", { name: "Open my profile", exact: true }).click();
  const previousPhoto = await avatar.getAttribute("src");
  await owner.getByLabel("Choose profile picture").setInputFiles(photo);
  await crop.getByRole("button", { name: "Save photo" }).click();
  await expect(avatar).not.toHaveAttribute("src", previousPhoto!);
  await owner.reload();
  await expect(avatar).toBeVisible();
  await owner.getByRole("button", { name: "Change profile picture" }).hover();
  await owner.getByRole("button", { name: "Remove photo" }).click();
  await expect(owner.getByRole("button", { name: "Add profile picture", exact: true })).toContainText("B");
  await owner.getByRole("link", { name: "Edit my profile", exact: true }).click();
  await expect(owner).toHaveURL(/\/profile\/edit$/);
  await owner.getByLabel("About you").fill("Frontend student and project owner.");
  await owner.getByRole("button", { name: "Save profile" }).click();
  await expect(owner).toHaveURL(/\/profile$/);
  await owner.reload();
  await expect(owner.getByText("Frontend student and project owner.", { exact: true })).toBeVisible();

  await register(member, "browser-member-" + suffix + "@example.test");
  await member.getByLabel("Full name", { exact: true }).fill("Browser Member");
  await member.getByLabel("Preferred project role").selectOption("Frontend Developer");
  await member.getByRole("combobox", { name: "Your skills" }).fill("React");
  await member.getByRole("option", { name: "React", exact: true }).click();
  await member.getByRole("checkbox", { name: "Weekday Evening", exact: true }).check();
  await member.getByRole("button", { name: "Save profile" }).click();
  await expect(member).toHaveURL(/\/dashboard$/);
  await owner.goto("/");
  await expect(owner).toHaveURL("/");
  await owner.goto("/dashboard");
  await expect(owner).toHaveURL(/\/dashboard$/);
  await owner.reload();
  await owner.getByRole("link", { name: /^Students/ }).click();
  await expect(owner.getByLabel("Search by name")).toBeVisible();
  await owner.getByLabel("Search by name").fill("Browser Member");
  await expect(owner.getByRole("heading", { name: "Browser Member" })).toBeVisible();
  await owner.getByRole("link", { name: "TeamFit home" }).click();
  await expect(owner).toHaveURL("/");
  await owner.goto("/dashboard");
  await owner.getByRole("link", { name: /My projects/ }).click();
  await owner.getByRole("link", { name: "Create project", exact: true }).click();
  await expect(owner).toHaveURL(/\/projects\/new$/);
  await owner.getByLabel("Project title").fill("Browser Team " + suffix);
  await owner.getByLabel("Description", { exact: true }).fill("A complete browser-tested student team.");
  await owner.getByLabel("Team size").fill("2");
  await owner.getByRole("combobox", { name: "Required skills" }).fill("React");
  await owner.getByRole("option", { name: "React", exact: true }).click();
  await owner.getByRole("checkbox", { name: "Frontend Developer", exact: true }).check();
  await owner.getByRole("checkbox", { name: "Weekday Evening", exact: true }).check();
  await owner.getByRole("button", { name: "Save project" }).click();
  await expect(owner.getByText("100/100", { exact: true })).toBeVisible();
  await expect(owner).toHaveURL(/\/projects\/\d+$/);
  const projectUrl = owner.url();
  await owner.screenshot({ path: "test-results/matching-desktop.png", fullPage: true });
  await owner.getByRole("button", { name: "Invite student", exact: true }).click();
  await expect(owner.getByRole("button", { name: "Invitation pending" })).toBeDisabled();
  await member.reload();
  await member.getByRole("link", { name: /Pending invitations/ }).click();
  await member.getByRole("button", { name: "Accept", exact: true }).click();
  await expect(member.getByText("You joined the team.", { exact: false })).toBeVisible();
  await owner.reload();
  await expect(owner.getByText("Open · 2/2 team members")).toBeVisible();
  await expect(owner.getByRole("heading", { name: "Team members" }).locator("..").getByText("Browser Member", { exact: true })).toBeVisible();

  // Tasks persist across page navigation; only the assignee or owner can change status.
  await owner.getByLabel("Task title", { exact: true }).fill("Build homepage");
  await owner.getByLabel("Task description", { exact: true }).fill("Create the public landing page.");
  await owner.getByRole("combobox", { name: "Assign to", exact: true }).selectOption({ label: "Browser Member" });
  await owner.getByRole("button", { name: "Create task", exact: true }).click();
  await expect(owner.getByRole("heading", { name: "Build homepage", exact: true })).toBeVisible();
  await member.getByRole("link", { name: "TeamFit home" }).click();
  await expect(member).toHaveURL("/");
  await member.goto("/dashboard");
  await member.getByRole("link", { name: /My projects/ }).click();
  await expect(member.getByRole("link", { name: "View project", exact: true })).toHaveCount(0);
  await member.getByRole("link", { name: "Joined projects", exact: true }).click();
  await member.getByRole("link", { name: "View project", exact: true }).click();
  await expect(member).toHaveURL(projectUrl);
  await expect(member.getByRole("checkbox", { name: "My assigned tasks only" })).toBeChecked();
  await expect(member.getByRole("button", { name: "Create task", exact: true })).toHaveCount(0);
  await member.getByLabel("Status for Build homepage", { exact: true }).selectOption("Done");
  await expect(member.getByText("1/1 tasks done · 100%", { exact: true })).toBeVisible();
  await member.reload();
  await expect(member.getByLabel("Status for Build homepage", { exact: true })).toHaveValue("Done");
  await owner.reload();
  await expect(owner.getByText("1/1 tasks done · 100%", { exact: true })).toBeVisible();

  // Check the completed state and mobile width without changing the visual design.
  await owner.getByRole("button", { name: "Edit project" }).click();
  await expect(owner).toHaveURL(/\/projects\/\d+\/edit$/);
  await owner.getByLabel("Project status").selectOption("Completed");
  await owner.getByRole("button", { name: "Save project" }).click();
  await expect(owner.getByText("Completed · 2/2 team members")).toBeVisible();
  await owner.reload();
  await expect(owner).toHaveURL(projectUrl);
  await expect(owner.getByText("Completed · 2/2 team members")).toBeVisible();
  await owner.screenshot({ path: "test-results/team-desktop.png", fullPage: true });
  await owner.setViewportSize({ width: 390, height: 844 });
  expect(await owner.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await owner.screenshot({ path: "test-results/team-mobile.png", fullPage: true });

  member.once("dialog", dialog => dialog.accept());
  await member.getByRole("button", { name: "Leave team", exact: true }).click();
  await expect(member.getByRole("region", { name: "Project tasks" })).toHaveCount(0);
  await owner.reload();
  await expect(owner.getByText("Assigned to: Unassigned", { exact: true })).toBeVisible();

  await owner.getByRole("button", { name: "Log out", exact: true }).click();
  await owner.getByRole("link", { name: "Login", exact: true }).click();
  await expect(owner.getByRole("heading", { name: "Welcome back to TeamFit" })).toBeVisible();
  await owner.getByLabel("Email", { exact: true }).fill("browser-owner-" + suffix + "@example.test");
  await owner.getByLabel("Password", { exact: true }).fill(password);
  await owner.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(owner).toHaveURL(/\/dashboard$/);
  await owner.reload();
  await expect(owner.getByRole("banner")).toContainText("browser");
  await owner.screenshot({ path: "test-results/dashboard-mobile.png", fullPage: true });
  await owner.goto("/workspace");
  await expect(owner).toHaveURL(/\/dashboard$/);
  await owner.goto("/login?next=https://untrusted.example");
  await expect(owner).toHaveURL(/\/dashboard$/);
  assertNoErrors();
  await ownerContext.close();
  await memberContext.close();
  function assertNoErrors() { expect(errors).toEqual([]); }
});
